COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"

# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8

# If left undefined, Portage's default behavior is to:
# - set the MAKEOPTS jobs value to the same number of threads returned by `nproc`
# - set the MAKEOPTS load-average value slightly above the number of threads returned by `nproc`, due to it being a damped value
# Please replace '4' as appropriate for the system (min(RAM/2GB, threads), or leave it unset.
MAKEOPTS="-j12 -l15"

# Toutes les licences en dehors de EULA sont acceptées
ACCEPT_LICENSE="* -@EULA"

# Options de langues
LINGUAS="fr"
L10N="fr"

# Grub sera installé pour un système UEFI
GRUB_PLATFORMS="efi-64"

# Pour que portage essaye de chercher des paquets binaires
FEATURES="${FEATURES} getbinpkg"
# Nécessaire pour la vérification de la signature des paquets (sans faire getuto)
FEATURES="${FEATURES} binpkg-request-signature"

# Pimp de portage et dl/install en parallèle
FEATURES="${FEATURES} candy news parallel-fetch parallel-install"

# Build des paquets en parallèle
EMERGE_DEFAULT_OPTS="--ask --verbose -j12 -l15 --quiet-build"

# Redirection des logs dans ce dossier
PORTAGE_LOGDIR="/var/log/portage"


# To sign the modules of kernels built from source enable the modules-sign USE flag
#USE="${USE} modules-sign secureboot"

# Default sbctl key locations
#MODULES_SIGN_KEY="/var/lib/sbctl/keys/db/db.key"
#MODULES_SIGN_CERT="/var/lib/sbctl/keys/db/db.pem"
#SECUREBOOT_SIGN_KEY="/var/lib/sbctl/keys/db/db.key"
#SECUREBOOT_SIGN_CERT="/var/lib/sbctl/keys/db/db.pem"

# An upgrade of a distribution kernel is capable of triggering an automatic rebuild 
# for external kernel modules installed by other packages (for example: sys-fs/zfs-kmod or x11-drivers/nvidia-drivers). 
# This automated behaviour is enabled by enabling the dist-kernel USE flag. 
# When required, this same flag will also trigger re-generation of the initramfs. 
USE="${USE} dist-kernel"

# Install shell completions for bash 
USE="${USE} bash-completion"

# enable flatpak support
USE="${USE} flatpak"

# enable networkmanager support
USE="${USE} networkmanager"

GENTOO_MIRRORS="http://ftp.free.fr/mirrors/ftp.gentoo.org/"
