context.modules = [
    {
        name = libpipewire-module-loopback
        args = {
            audio.channels = 2
            audio.position = [ FL FR ]

            capture.props = {
                media.class = Audio/Sink
                node.name = virtual_sink1
                node.description = "Sortie Audio Virtuelle 1"
                node.virtual = true
                object.linger = true
            }

            playback.props = {
                node.name = virtual_sink1.output
                node.passive = true
                target.object = "@DEFAULT_SINK@"
            }
        }
    }

    {
        name = libpipewire-module-loopback
        args = {
            audio.channels = 2
            audio.position = [ FL FR ]

            capture.props = {
                media.class = Audio/Sink
                node.name = virtual_sink2
                node.description = "Sortie Audio Virtuelle 2"
                node.virtual = true
                object.linger = true
            }

            playback.props = {
                node.name = virtual_sink2.output
                node.passive = true
                target.object = "@DEFAULT_SINK@"
            }
        }
    }

    {
        name = libpipewire-module-loopback
        args = {
            audio.channels = 2
            audio.position = [ FL FR ]

            capture.props = {
                media.class = Audio/Sink
                node.name = virtual_sink3
                node.description = "Sortie Audio Virtuelle 3"
                node.virtual = true
                object.linger = true
            }

            playback.props = {
                node.name = virtual_sink3.output
                node.passive = true
                target.object = "@DEFAULT_SINK@"
            }
        }
    }

    {
        name = libpipewire-module-loopback
        args = {
            audio.channels = 2
            audio.position = [ FL FR ]

            capture.props = {
                media.class = Audio/Sink
                node.name = virtual_sink4
                node.description = "Sortie Audio Virtuelle 4"
                node.virtual = true
                object.linger = true
            }

            playback.props = {
                node.name = virtual_sink4.output
                node.passive = true
                target.object = "@DEFAULT_SINK@"
            }
        }
    }

]
