context.modules = [
  {
    name = libpipewire-module-loopback
    args = {
      node.description = "Virtual Microphone"

      capture.props = {
        node.name = "virtual_mic_input"
        media.class = "Audio/Sink"
	node.description = "Entrée Audio Virtuelle"
        node.virtual = true
        object.linger = true

      }

      playback.props = {
        node.name = "virtual_mic"
	node.passive = true
        media.class = "Audio/Source"
      }
    }
  }
]
